name: sync
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Get MySQL
        run: |
          apt-get update
          apt-get -y install default-libmysqlclient-dev build-essential
      - name: Install Dependencies
        working-directory: sync-service
        run: |
          pip install -r requirements.txt
      - name: Test
        run: |
          echo "github actions hello!"
