name: sync
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Get MySQL
        run: |
          sudo apt-get update
          sudo apt-get -y install default-libmysqlclient-dev build-essential python3-pip
      - name: Install Dependencies
        working-directory: sync-service
        run: |
          pip install -r requirements.txt
      - name: Synchronise Database
        env:
          HOST: ${{secrets.HOST}}
          USERNAME: ${{secrets.USERNAME}}
          DATABASE: ${{secrets.DATABASE}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: |
          flask --app sync-service/api sync-db
